blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://forum.syncthing.net/
    about: Ask questions and discuss with other community members
  - name: Issue on Android
    url: https://github.com/syncthing/syncthing-android/issues/
    about: The Android app has its own issue tracker
  - name: Report a security problem
    url: https://syncthing.net/security/
    about: Security issues require specific handling